export const REQUEST_VIDEOS = 'REQUEST_VIDEOS';
export const SELECT_VIDEO = 'SELECT_VIDEO';
export const REQUEST_KVIDEOS = 'REQUEST_KVIDEOS';
export const SELECT_KVIDEO = 'SELECT_KVIDEO';
export const REQUEST_FVIDEOS = 'REQUEST_FVIDEOS';
export const SELECT_FVIDEO  = 'SELECT_FVIDEO';
export const ADD_SVIDEO = 'ADD_SVIDEO';
export const SELECT_SVIDEO = 'SELECT_SVIDEO';



